### PR TITLE
fix(frontend): change table header text color from white to black

### LINKED ISSUE #16: [Suggestion] Change table header colors from white to black
As white text on the bright lime is hard to read. The CSS is somehow auto-generated and the class defined [here](https://github.com/ravenclaw900/DietPi-Dashboard/blob/main/src/frontend/windi.config.ts), right?

So I guess there is no way to add `color: #000` to the class? Then I'd add it manually to each table header.

### PR DESCRIPTION
**Pull request by MichaIng**
Would be certainly nicer to add this style via classes, e.g. bind it to the `bg-dplime` class as white text on this background never looks good. However, the class seems auto-generated so until someone knows an elegant solution, here the quick & dirty one 😉.

Fixes #16

### CODE REVIEW

**Comment by MichaIng** [comment]
Build action on my branch: https://github.com/MichaIng/DietPi-Dashboard/runs/4126774453?check_suite_focus=true

Whoops, I accidentally left the old commit header in place, somehow. "Quash & Merge" to adjust it when merging into the base branch.

File: src/frontend/src/pages/Process.svelte [hunk 1]
```diff
@@ -232,7 +232,7 @@
         <table
             class="border border-gray-300 dark:border-gray-700 w-full table-fixed break-words overflow-x-scroll"
         >
-            <tr class="bg-dplime">
+            <tr class="bg-dplime" style="color:#000">
```
Comment (ravenclaw900) [inline src/frontend/src/pages/Process.svelte:235]: Please use the `text-black` class instead of manually setting the style. This goes for the rest of them too.

**Comment by ravenclaw900** [comment]
Also, instead of applying that change, we do the same thing as the [`btn` class](https://github.com/ravenclaw900/DietPi-Dashboard/blob/main/src/frontend/windi.config.ts#L16). A `table-header` shortcut would work, with both the `bg-dplime` and `text-black` classes.

**Comment by MichaIng** [comment]
Does it mean we define:
```
"table-header": "bg-dplime text-black"
```
And then set `class="table-header"` or:
```
"table-header": "class='cbg-dplime text-black'"
```
Not sure where/how those shortcuts are expanded.

**Comment by ravenclaw900** [comment]
Yes, define `"table-header": "bg-dplime text-black"` in the shortcuts section. Then use `class="table-header"` in the code. They're expanded when the code is built, `table-header` will be replaced with the aforementioned classes.

**Comment by MichaIng** [comment]
CI: https://github.com/MichaIng/DietPi-Dashboard/runs/4127299283?check_suite_focus=true

**Comment by ravenclaw900** [comment]
CI is working here now.

**Comment by MichaIng** [comment]
You solved it by adding the pull request event? I wonder whether its the same on our docs and website repos. I remember I had the issue when adding both events that pushing to a new branch and opening a PR on the origin repo, the action ran two times, once for the commit and once for opening the PR, too much overhead and caused issues when doing all link checks concurrently.

It is the same here. The above tracked build was on your branch for the pull request event. Concurrently there runs the build for the push event on my branch 🤔: https://github.com/MichaIng/DietPi-Dashboard/runs/4127469775?check_suite_focus=true

Best would be if the run for the push event on my branch was tracked here.

**Comment by ravenclaw900** [comment]
The main solution for that seems to be having push only run on the main branch, while also having pull request.

**Comment by MichaIng** [comment]
I think `pull_request` event is not triggered when commits are pushed to an open PR, while we then want to run the PR. Probably it is okay to leave it with `push` event only and track the CI result on the remote repo. We can also ask GitHub devs about this. It shouldn't be a problem to track the remote CI on the PR, and it simply makes sense.

**Review by ravenclaw900 — APPROVED** [review]

**Comment by ravenclaw900** [comment]
It does look like it's triggered:
> By default, a workflow only runs when a pull_request's activity type is opened, synchronize, or reopened.

The `synchronize` type is when a commit is pushed. However, I'll leave it like we have it for new.
